name: Get Version

on:
  push:
  release:

jobs:
  test:
    runs-on: ubuntu-latest

  env:
    VERSION: ${{ github.event.release.tagName }}
    DATE: ${{ github.event.release.createdAt }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo information
        run: echo "Tag Name = ${{env.VERSION}}"
