name: Get Version

on:
  push:

env:
  VERSION: "Version-Not-Available"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Extract version from tag
      #   uses: damienaicheh/extract-version-from-tag-action@v1.1.0

      # - name: Set Version
      #   run: echo "VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV

      # - name: Echo Version
      #   run: echo "Version = $VERSION"

      - uses: actions/checkout@v1
      - name: "call action"
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "release"
          view_top: 1
      - name: "Print result"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "name: ${{ steps.last_release.outputs.name }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_at }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"
          echo "url: ${{ steps.last_release.outputs.url }}"
          echo "html_url: ${{ steps.last_release.outputs.html_url }}"
