name: Get Version

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo Tag Name
        run: echo "Tag Name = ${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Echo Release Date
        run: echo "Release Date = ${{ github.event.release.created_at }}" >> $GITHUB_ENV
