name: Get Version

on:
  release:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{github.event.release.tag_name}}
      DATE: ${{github.event.release.created_at}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo Tag Name
        run: echo "Tag Name = ${{ env.VERSION }}"

      - name: Echo Release Date
        run: echo "Release Date = ${{ env.DATE }}"

      - name: If file Exist
        if: ${{ hashFiles('version.json') != '' }}
        run: echo "`jq '.Version=${{env.VERSION}} .Date=${{env.DATE}}' version.json`" > version.json ; echo 'File Exist'

      - name: If file Not Exist
        if: ${{ hashFiles('version.json') == '' }}
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "version.json"
          json: '{"Version":${{env.VERSION}}, "Date":${{env.DATE}}}'

      - name:
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Changed files
