name: Get Version

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{github.event.release.tag_name}}
      DATE: ${{github.event.release.created_at}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo Tag Name
        run: echo "Tag Name = ${{ env.VERSION }}"

      - name: Echo Release Date
        run: echo "Release Date = ${{ env.DATE }}"
