name: Get Version

on:
  push:
  release:

# env:
#   VERSION: ${{ github.event.release.tagName }}
#   DATE: ${{ github.event.release.createdAt }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo information
        run: |
          echo "Tag Name = ${{ github.event.release.tag}}" >> $GITHUB_ENV
          echo "Tag Name = ${{ github.event.release.createdAt}}" >> $GITHUB_ENV
