name: Get Version

on:
  push:
  release:

env:
  VERSION: ${{ github.event.release.tag_name }}
  DATE: ${{ github.event.release.createdAt }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Print Release Information
        run: |
          touch .env
          echo "Version=${{ env.VERSION }}" >> .env
          cat .env
