name: Get Version

on:
  push:

env:
  VERSION: "Version-Not-Available"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gets latest creaetd release info
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Echo Release Version
        run: echo ${{steps.latest_release_info.outputs.tag_name}}

      - name: Echo Release Date
        run: echo ${{steps.latest_release_info.outputs.created_at}}
