name: Get Version

on:
  release:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{github.event.release.tag_name}}
      DATE: ${{github.event.release.created_at}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo Tag Name
        run: echo "Tag Name = ${{ env.VERSION }}"

      - name: Echo Release Date
        run: echo "Release Date = ${{ env.DATE }}"

      - name: If file Exist
        if: ${{ hashFiles('version.json') != '' }}
        run: echo "`jq '.Version=${{env.VERSION}} .Date=${{env.DATE}}' version.json`" > version.json ; echo 'File Exist'

      - name: If file Not Exist
        if: ${{ hashFiles('version.json') == '' }}
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "version.json"
          json: '{"Version":${{env.VERSION}}, "Date":${{env.DATE}}}'

      - name: Commit changes
        run: |
          git config --global user.email "imkevinisme@gmail.com"
          git config --global user.name "GitHub Actions"
          git add version.json
          git commit -m "Update version.json"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
