name: Get Version

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{github.ref_name}}
      DATE: ${{github.event.pusher.date}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo Tag Name
        run: echo "Tag Name = ${{ env.VERSION }}"

      - name: Echo Release Date
        run: echo "Release Date = ${{ env.DATE }}"
