name: Get Version

on:
  push:

env:
  VERSION: "Version-Not-Available"
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Extract version from tag
      #   uses: damienaicheh/extract-version-from-tag-action@v1.1.0

      # - name: Set Version
      #   run: echo "VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV

      # - name: Echo Version
      #   run: echo "Version = $VERSION"

      - name: Get latest release
        id: latest_release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ github.token }}
          latest: true

      - name: Echo Release Tag
        run: echo "Version = $tag_name"
