name: Get Version

on:
  push:
  release:

jobs:
  checks:
    runs-on: ubuntu-latest

    env:
      # database ENV CAN BE ONLY  PROD,DEV,UAT,STAGING
      APP_VERSION: ${{ github.event.release.tag_name }}

    steps:
      - name: "Create env file"
        run: |
          touch .env
          echo "NEXT_PUBLIC_APP_VERSION=${{ env.APP_VERSION }}" >> .env
          cat .env
