name: Get Version

on:
  push:
  release:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo information
        run: |
          echo "Tag Name = ${{ github.event.release.name }}" >> $GITHUB_ENV
          echo "Tag Name = ${{ github.event.release.created_at }}" >> $GITHUB_ENV
