name: Get Version

on:
  push:

env:
  VERSION: "Version-Not-Available"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.1.0

      - name: Set Version
        run: echo "::set-env name=VERSION::&MAJOR.$MINOR.$PATCH"

      - name: Echo Version
        run: echo "Version = $VERSION"
